name: Build and Release Flatpak-Compose

on:
  push:
    tags:
      - '*'
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows] # List of operating systems
        arch: [amd64, arm64, arm] # List of architectures
        exclude:
        # excludes node 8 on macOS
        - os: darwin
          arch: arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.4'

      - name: Install dependencies
        run: |
          go mod download

      - name: Build flatpak-compose
        run: |
          GOARCH=${{ matrix.arch }} GOOS=${{ matrix.os }} go build -o flatpak-compose-${{ matrix.os }}-${{ matrix.arch }} ./cmd/main.go

      - name: Zip artifacts
        run: |
          zip flatpak-compose-${{ matrix.os }}-${{ matrix.arch }}.zip flatpak-compose-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-compose-${{ matrix.os }}-${{ matrix.arch }}
          path: flatpak-compose-${{ matrix.os }}-${{ matrix.arch }}.zip
  create_release:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ github.ref }}
          draft: false
          prerelease: false

  upload_assets:
    needs: create_release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows] # List of operating systems
        arch: [amd64, arm64, arm] # List of architectures
        exclude:
          - os: darwin
            arch: arm
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: flatpak-compose-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./flatpak-compose-${{ matrix.os }}-${{ matrix.arch }}.zip
          asset_name: flatpak-compose-${{ matrix.os }}-${{ matrix.arch }}.zip
          asset_content_type: application/zip
